select * from customers_raw
select * from employee_raw
select * from inventory_transactions_raw
select * from orders_raw
select * from order_details_raw
select * from payments_raw
select * from payment_methods_raw
select * from products_raw
select * from purchase_orders_raw
select * from shipping_methods_raw
select * from suppliers_raw
